# ---------------------------------------------------------------------------
# Define organzations required by the Custodian Asset usecase.
# Organizations - 6
# Orderer - 1
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    # -----------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # -----------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # -------------------------------------------------------------------------
  # Org1 - Investor
  # -------------------------------------------------------------------------
  - Name: Investor 
    Domain: investor.example.com
    Template:
      Count: 1
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
    # -----------------------------------------------------------------------
    # "Users"
    # -----------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # -----------------------------------------------------------------------
    Users:
      Count: 1
  # -------------------------------------------------------------------------
  # Org2 - Custodian
  # -------------------------------------------------------------------------
  - Name: Custodian
    Domain: custodian.example.com
    Template:
      Count: 1
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
    # -----------------------------------------------------------------------
    # "Users"
    # -----------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # -----------------------------------------------------------------------
    Users:
      Count: 1
  # -------------------------------------------------------------------------
  # Org3 - Exchange
  # -------------------------------------------------------------------------
  - Name: Exchange
    Domain: exchange.example.com
    Template:
      Count: 1
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
    # -----------------------------------------------------------------------
    # "Users"
    # -----------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # -----------------------------------------------------------------------
    Users:
      Count: 1
  # -------------------------------------------------------------------------
  # Org4 - Bank
  # -------------------------------------------------------------------------
  - Name: Bank
    Domain: bank.example.com
    Template:
      Count: 1
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
    # -----------------------------------------------------------------------
    # "Users"
    # -----------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # -----------------------------------------------------------------------
    Users:
      Count: 1
  # -------------------------------------------------------------------------
  # Org5 - Depository
  # -------------------------------------------------------------------------
  - Name: Depository
    Domain: depository.example.com
    Template:
      Count: 1
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
    # -----------------------------------------------------------------------
    # "Users"
    # -----------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # -----------------------------------------------------------------------
    Users:
      Count: 1
  # -------------------------------------------------------------------------
  # Org6 - Regulator
  # -------------------------------------------------------------------------
  - Name: Regulator
    Domain: regulator.example.com
    Template:
      Count: 1
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
    # -----------------------------------------------------------------------
    # "Users"
    # -----------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # -----------------------------------------------------------------------
    Users:
      Count: 1

